### ISSUE TITLE
CamDesk doesn't stay on top if an application is set to fullscreen on Ubuntu

### ISSUE THREAD

**Issue by JackHack96** [michaelsboost/CamDesk#2]
I found a bug in CamDesk: if I set it to be always on top and then I run a fullscreen application, e.g. Firefox in full screen mode, it disappears.
I searched the web and there was a bug report in Compiz (https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/789827), but the developer said it has to be fixed in the application (for example Onboard really stays always on top)

**Comment by michaelsboost** [comment]
It's been years since I've touched Ubuntu. 

Can anyone confirm if the release of [2016-03-07](https://sourceforge.net/projects/camdesk/files/1.1/CamDesk-1.1-lin32.zip/download) or [2015-10-01](https://sourceforge.net/projects/camdesk/files/1.1/camdesk-1.1-lin.tar.gz/download) solves this issue?
